sudo: false
language: c++

# Defer the actual build script to travis-build.sh
script: Build/travis-build.sh

stages:
  - build
  - notify

# Notify Discord when any job fails.
after_failure: Build/notify-discord.sh failure $DISCORD_WEBHOOK_URL

# Build configuration matrix
jobs:
  include:
    - stage: build
      name: "OSX/Xcode10.3"
      os: osx
      osx_image: xcode10.3
      compiler: clang
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=NO ENABLE_UBSAN=NO ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=YES

    - stage: build
      name: "OSX/Xcode11"
      os: osx
      osx_image: xcode11
      compiler: clang
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=NO ENABLE_UBSAN=NO ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=YES
    
    - stage: build
      name: "UbuntuXenial/GCC"
      os: linux
      dist: xenial
      compiler: gcc
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=NO ENABLE_UBSAN=NO ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=YES

    - stage: build
      name: "UbuntuXenial/Clang"
      os: linux
      dist: xenial
      compiler: clang
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=NO ENABLE_UBSAN=NO ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=YES

    - stage: build
      name: "UbuntuBionic/GCC"
      os: linux
      dist: bionic
      compiler: gcc
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=NO ENABLE_UBSAN=NO ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=YES

    - stage: build
      name: "UbuntuBionic/Clang"
      os: linux
      dist: bionic
      compiler: clang
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=NO ENABLE_UBSAN=NO ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=YES

    - stage: build
      name: "UbuntuBionic/GCC STATIC_LINKING"
      os: linux
      dist: bionic
      compiler: gcc
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=YES ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=NO ENABLE_UBSAN=NO ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=YES

    - stage: build
      name: "UbuntuBionic/GCC RELEASE_ASSERTS"
      os: linux
      dist: bionic
      compiler: gcc
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=YES ENABLE_ASAN=NO ENABLE_UBSAN=NO ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=YES

    - stage: build
      name: "UbuntuBionic/GCC ASAN"
      os: linux
      dist: bionic
      compiler: gcc
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=YES ENABLE_UBSAN=NO ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=NO

    - stage: build
      name: "UbuntuBionic/GCC UBSAN"
      os: linux
      dist: bionic
      compiler: gcc
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=NO ENABLE_UBSAN=YES ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=NO

    - stage: build
      name: "UbuntuBionic/Clang ASAN"
      os: linux
      dist: bionic
      compiler: clang
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=YES ENABLE_UBSAN=NO ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=NO

    - stage: build
      name: "UbuntuBionic/Clang UBSAN"
      os: linux
      dist: bionic
      compiler: clang
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=NO ENABLE_UBSAN=YES ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=NO

    - stage: build
      name: "UbuntuBionic/Clang TSAN"
      os: linux
      dist: bionic
      compiler: clang
      env: ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=NO ENABLE_UBSAN=YES ENABLE_LIBFUZZER=NO ENABLE_TSAN=YES ENABLE_RELEASE=YES ENABLE_DEBUG=NO

    - stage: build
      name: "UbuntuBionic/GCC ENABLE_RUNTIME=NO"
      os: linux
      dist: bionic
      compiler: gcc
      env: ENABLE_RUNTIME=NO ENABLE_STATIC_LINKING=NO ENABLE_RELEASE_ASSERTS=NO ENABLE_ASAN=NO ENABLE_UBSAN=NO ENABLE_LIBFUZZER=NO ENABLE_TSAN=NO ENABLE_RELEASE=YES ENABLE_DEBUG=YES

    - stage: notify
      name: "Notify Discord"
      os: linux
      dist: bionic
      install: skip
      script: Build/notify-discord.sh success $DISCORD_WEBHOOK_URL